let FieldApp = {
  SignUp: {
    mutation: {
      fullName,
      email,
      password,
      mobileNumber,
      role: ['ADMIN', 'SALESMAN'],
    },
    mutationOutput: { accessToken, refreshToken, me },
  },
  Login: {
    mutation: { email, password },
    mutationOutput: { accessToken, refreshToken, me },
  },
  Product: {
    mutation: { productName, productWeight, maker, category, mfgDate, expDate },
    mutationOutput: {
      productName,
      productWeight,
      maker,
      category,
      mfgDate,
      expDate,
      createdAt,
      updatedAt,
    },
    query: {
      list: {
        productName,
        productWeight,
        maker,
        category,
        mfgDate,
        expDate,
        createdAt,
        updatedAt,
      },
    },
  },
  Customer: {
    mutation: {
      customerName,
      customerAddress,
      customerMobileNumber,
      addedBySalesman,
    },
    mutationOutput: {
      customerName,
      customerAddress,
      customerMobileNumber,
      addedBySalesman,
      createdAt,
      updatedAt,
    },
    query: {
      list: {
        customerName,
        customerAddress,
        customerMobileNumber,
        addedBySalesman,
        createdAt,
        updatedAt,
      },
    },
  },
  Order: {
    mutation: {
      orderNumber,
      customerName,
      customerAddress,
      customerMobileNumber,
      orderedProducts: { productName, productWeight, quantity },
      quantity,
      paymentStatus,
    },
    mutationOutput: {
      orderNumber,
      customerName,
      customerAddress,
      customerMobileNumber,
      orderedProducts: { productName, productWeight, quantity },
      quantity,
      paymentStatus,
      createdAt,
      updatedAt,
    },
    query: {
      list: {
        orderNumber,
        customerName,
        customerAddress,
        customerMobileNumber,
        orderedProducts: { productName, productWeight, quantity },
        quantity,
        paymentStatus,
        createdAt,
        updatedAt,
      },
    },
  },
  Sample: {
    mutation: {
      sampleName,
      sampleQuantity,
      givenToWhom: ['CUSTOMER', 'SALESMAN'],
      givenTo,
      givenByRole: ['SALESMAN', 'ADMIN'],
      givenBy,
    },
    mutationOutput: {
      sampleName,
      sampleQuantity,
      givenToWhom: ['CUSTOMER', 'SALESMAN'],
      givenTo,
      givenByRole: ['SALESMAN', 'ADMIN'],
      givenBy,
      createdAt,
      updatedAt,
    },
    query: {
      list: {
        sampleName,
        sampleQuantity,
        givenToWhom: ['CUSTOMER', 'SALESMAN'],
        givenTo,
        givenByRole: ['SALESMAN', 'ADMIN'],
        givenBy,
        createdAt,
        updatedAt,
      },
    },
  },
  DayPlan: {
    mutation: {
      taskName,
      taskDescription,
      isCompleted: [true, false],
      plannerName,
      reason,
      completedAt,
      location,
    },
    mutationOutput: {
      taskName,
      taskDescription,
      isCompleted: [true, false],
      plannerName,
      reason,
      completedAt,
      location,
      createdAt,
      updatedAt,
    },
    query: {
      list: {
        taskName,
        taskDescription,
        isCompleted: [true, false],
        plannerName,
        reason,
        completedAt,
        location,
        createdAt,
        updatedAt,
      },
    },
  },
  Attendence: {
    mutation: {
      salesmanName: ["relate to user with role 'SALESMAN'"],
      timeCheckedIn,
      timeCheckedOut,
      location,
    },
    mutationOutput: {
      salesmanName: ["relate to user with role 'SALESMAN'"],
      timeCheckedIn,
      timeCheckedOut,
      location,
      createdAt,
      updatedAt,
    },
    query: {
      list: {
        salesmanName: ["relate to user with role 'SALESMAN'"],
        timeCheckedIn,
        timeCheckedOut,
        location,
        createdAt,
        updatedAt,
      },
    },
  },
  StoreVisit: {
    mutation: {
      storeName,
      location,
      address,
      location,
      salesmanName: ["relate to user with role 'SALESMAN'"],
      isCustomer: [true, false],
    },
    mutationOutput: {
      storeName,
      location,
      address,
      location,
      salesmanName: ["relate to user with role 'SALESMAN'"],
      isCustomer: [true, false],
      createdAt,
      updatedAt,
    },
    query: {
      list: {
        storeName,
        location,
        address,
        location,
        salesmanName: ["relate to user with role 'SALESMAN'"],
        isCustomer: [true, false],
        createdAt,
        updatedAt,
      },
    },
  },
  Location: {
    mutation: {
      longitude,
      latitude,
      address,
      nameOfLocation,
    },
    mutationOutput: {
      longitude,
      latitude,
      address,
      nameOfLocation,
      createdAt,
      updatedAt,
    },
    query: {
      list: {
        longitude,
        latitude,
        address,
        nameOfLocation,
        createdAt,
        updatedAt,
      },
    },
  },
};
